name: Deploy

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment: env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          cd ./gdrive
          env
          ./scrape.sh
          cat gdown_logs.txt
          ls -hal
        env:
          GDRIVE_FOLDER: ${{ secrets.GDRIVE_FOLDER }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
      - run: |
          cd ./gdrive
          node download.ts
          ls -hal
      - run: |
          npm ci
          npm run build
      - uses: actions/configure-pages@v5