name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 */2 * * *"
    - cron: "1 23 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment: ghpages
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo timedatectl set-timezone "Europe/Budapest"
          echo TZ="Europe/Budapest" >> $GITHUB_ENV
      - uses: actions/checkout@v6
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - run: |
          sudo apt install imagemagick
          cd ./gdrive/
          ./download_and_convert.sh
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"
      - run: |
          npm ci
          npm run build
          ls -hal ./dist/
      - uses: actions/configure-pages@v6.0.0
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
      - uses: actions/deploy-pages@v5
