name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 */2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment: ghpages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - run: |
          rclone copy gdrive: ./gdrive/ --drive-export-formats txt
          ls -hal ./gdrive/
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "npm"
      - run: |
          npm ci
          npm run build
          ls -hal ./dist/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - uses: actions/deploy-pages@v4
